#!/usr/bin/env bash
# validate_commit.sh - Validate a commit message against conventional commits format
# Usage: bash validate_commit.sh "feat(scope): message"
#        bash validate_commit.sh --file .git/COMMIT_EDITMSG

set -euo pipefail

MSG=""
if [[ "${1:-}" == "--file" ]]; then
  [[ -f "${2:-}" ]] || { echo "ERROR: File not found: ${2:-}"; exit 1; }
  MSG=$(head -1 "$2")
else
  MSG="${1:-}"
fi

[[ -z "$MSG" ]] && { echo "ERROR: No commit message provided"; exit 1; }

SUBJECT=$(echo "$MSG" | head -1)

# Check length
if [[ ${#SUBJECT} -gt 72 ]]; then
  echo "FAIL: Subject line is ${#SUBJECT} chars (max 72)"
  exit 1
fi

# Check conventional commit format: type(scope): subject  OR  type: subject
PATTERN='^(feat|fix|refactor|docs|test|chore|backup|ci|style|perf|build|revert)(\([a-zA-Z0-9._-]+\))?: .+'
if ! echo "$SUBJECT" | grep -qE "$PATTERN"; then
  echo "FAIL: Does not match conventional commits format"
  echo "Expected: type(scope): description"
  echo "Types: feat, fix, refactor, docs, test, chore, backup, ci, style, perf, build, revert"
  echo "Got: $SUBJECT"
  exit 1
fi

# Check no trailing period
if echo "$SUBJECT" | grep -qE '\.$'; then
  echo "FAIL: Subject should not end with a period"
  exit 1
fi

# Check no AI attribution
if echo "$MSG" | grep -qiE 'Co-Authored-By:.*Claude|Generated with.*Claude|Generated by AI'; then
  echo "FAIL: No AI attribution markers allowed"
  exit 1
fi

echo "OK: $SUBJECT"
